import { describe, expect, it } from "bun:test";
import { isReadOnlyBashCommand } from "../../src/tools/bash-readonly";

describe("isReadOnlyBashCommand", () => {
	it.each([
		"ls -la",
		"cat package.json",
		"git status",
		"git log --oneline -5",
		"git diff HEAD~1",
		"git branch -a",
		"git stash list",
		"git remote -v",
		'find . -name "*.ts"',
		"grep -rn foo src",
		"sort -u file",
		"/bin/ls",
		"  git status  ",
		"git diff --output-indicator-new=+",
		"file -c",
		"rg -o pat",
		"grep -o pat f",
	])("accepts a provably read-only command: %s", command => {
		expect(isReadOnlyBashCommand(command)).toBe(true);
	});

	it.each([
		"rm -rf build",
		"git commit -m x",
		"git push",
		"git checkout main",
		"git reset --hard",
		"git branch new",
		"git tag v1",
		"git stash",
		"git stash push",
		"git remote add origin u",
		"chmod +x f",
		"tee out.txt",
		"dd if=a of=b",
		"sort -o out.txt in.txt",
		"sort --output=out.txt in.txt",
		"git diff --output=out",
		"git log --output=out",
		"git diff --output out",
		"git shortlog --output=out",
		"git shortlog -o out",
		"tree -o out",
		"tree --output out",
		"rg --pre=sh pat",
		"git grep -Ocat pat",
		"git grep --open-files-in-pager=cat pat",
		"file -C",
		"file --compile",
		"sort -oout in",
		"uniq in",
		"uniq in.txt out.txt",
		"xxd in",
		"xxd -l 16 in",
		"find . -delete",
		"find . -exec rm {} +",
		"find . -fprint x",
		"ls > out",
		"ls | wc -l",
		"ls && rm -rf x",
		"echo $(date)",
		"echo `date`",
		"ls ; pwd",
		"ls\npwd",
		"env ls",
		"xargs ls",
		"timeout 1 ls",
		"bash -c 'ls'",
		"python -c 'print(1)'",
		"node -e 'x'",
		"sudo ls",
		"",
		"   ",
	])("rejects a command that is not provably read-only: %s", command => {
		expect(isReadOnlyBashCommand(command)).toBe(false);
	});
});
